// ============================================================
// 脑区能力契约注册表
// 对应文档: 08-dynamic-orchestration.md Section 一
// ============================================================

import { CapabilityContract } from "../types";

function defaultHealth() {
  return {
    recent_success_rate: 1.0,
    avg_latency_ms: 0,
    timeout_ratio: 0,
    last_healthy_check: new Date().toISOString(),
  };
}

export const REGION_CONTRACTS: Record<string, CapabilityContract> = {
  amygdala: {
    region: "amygdala",
    can: ["input_scanning", "threat_detection", "content_filtering"],
    cannot: [],
    prefers: ["input_scanning"],
    blacklist: ["response_generation", "strategy_generation"],
    typical_latency_ms: 5,
    max_latency_ms: 3000,
    requires_llm: true,
    concurrent_capable: false,
    must_wait_for: [],
    optional_input_from: [],
    health: defaultHealth(),
  },

  parietal: {
    region: "parietal",
    can: ["intent_extraction", "attention_allocation", "entity_recognition", "structural_analysis", "tone_detection"],
    cannot: ["strategy_generation", "action_decision"],
    prefers: ["intent_extraction", "attention_allocation"],
    blacklist: [],
    typical_latency_ms: 5000,
    max_latency_ms: 5000,
    requires_llm: true,
    concurrent_capable: true,
    must_wait_for: ["amygdala"],
    optional_input_from: [],
    health: defaultHealth(),
  },

  temporal: {
    region: "temporal",
    can: ["semantic_decomposition", "domain_classification", "novelty_assessment", "complexity_estimation", "entity_relation_mapping"],
    cannot: ["strategy_generation", "content_filtering"],
    prefers: ["semantic_decomposition", "domain_classification"],
    blacklist: [],
    typical_latency_ms: 12000,
    max_latency_ms: 12000,
    requires_llm: true,
    concurrent_capable: true,
    must_wait_for: ["hippocampus"],
    optional_input_from: [],
    health: defaultHealth(),
  },

  frontal: {
    region: "frontal",
    can: ["strategy_generation", "pre_judgment", "risk_assessment", "step_decomposition", "multi_perspective_scoring"],
    cannot: ["content_filtering"],
    prefers: ["strategy_generation", "risk_assessment"],
    blacklist: [],
    typical_latency_ms: 20000,
    max_latency_ms: 20000,
    requires_llm: true,
    concurrent_capable: true,
    must_wait_for: ["temporal"],
    optional_input_from: ["hippocampus"],
    health: defaultHealth(),
  },

  hippocampus: {
    region: "hippocampus",
    can: ["memory_retrieval", "memory_consolidation", "preference_learning", "semantic_graph_query", "pattern_recognition"],
    cannot: ["strategy_generation", "content_filtering"],
    prefers: ["memory_retrieval"],
    blacklist: [],
    typical_latency_ms: 3000,
    max_latency_ms: 3000,
    requires_llm: false,
    concurrent_capable: true,
    must_wait_for: ["amygdala"],
    optional_input_from: ["parietal"],
    health: defaultHealth(),
  },

  hermes: {
    region: "hermes",
    can: ["signal_fusion", "conflict_resolution", "action_decision", "response_generation", "tone_adaptation"],
    cannot: [],
    prefers: ["signal_fusion", "response_generation"],
    blacklist: [],
    typical_latency_ms: 5000,
    max_latency_ms: 10000,
    requires_llm: true,
    concurrent_capable: false,
    must_wait_for: ["parietal", "temporal", "frontal", "hippocampus", "amygdala"],
    optional_input_from: [],
    health: defaultHealth(),
  },

  motor: {
    region: "motor",
    can: ["action_planning", "tool_dispatch", "reply_execution"],
    cannot: ["strategy_generation", "content_filtering", "intent_extraction"],
    prefers: ["reply_execution"],
    blacklist: [],
    typical_latency_ms: 1,
    max_latency_ms: 100,
    requires_llm: false,
    concurrent_capable: false,
    must_wait_for: ["hermes"],
    optional_input_from: [],
    health: defaultHealth(),
  },

  acc: {
    region: "acc",
    can: ["conflict_resolution"],
    cannot: ["strategy_generation", "response_generation", "content_filtering"],
    prefers: ["conflict_resolution"],
    blacklist: [],
    typical_latency_ms: 1,
    max_latency_ms: 100,
    requires_llm: false,
    concurrent_capable: true,
    must_wait_for: ["parietal", "temporal", "frontal"],
    optional_input_from: [],
    health: defaultHealth(),
  },

  bg: {
    region: "bg",
    can: ["q_learning", "reward_computation"],
    cannot: ["strategy_generation", "response_generation", "content_filtering"],
    prefers: ["q_learning"],
    blacklist: [],
    typical_latency_ms: 1,
    max_latency_ms: 100,
    requires_llm: false,
    concurrent_capable: true,
    must_wait_for: [],
    optional_input_from: ["hermes"],
    health: defaultHealth(),
  },

  cerebellum: {
    region: "cerebellum",
    can: ["skill_tracking", "error_analysis", "prompt_optimization", "weight_optimization", "timeout_optimization"],
    cannot: ["strategy_generation", "response_generation", "content_filtering"],
    prefers: ["skill_tracking", "weight_optimization"],
    blacklist: [],
    typical_latency_ms: 1,
    max_latency_ms: 100,
    requires_llm: false,
    concurrent_capable: true,
    must_wait_for: [],
    optional_input_from: ["hermes"],
    health: defaultHealth(),
  },

  dmn: {
    region: "dmn",
    can: ["self_reflection"],
    cannot: ["strategy_generation", "action_decision", "content_filtering"],
    prefers: ["self_reflection"],
    blacklist: [],
    typical_latency_ms: 8000,
    max_latency_ms: 8000,
    requires_llm: true,
    concurrent_capable: true,
    must_wait_for: [],
    optional_input_from: ["hermes"],
    health: defaultHealth(),
  },

  thalamus: {
    region: "thalamus",
    can: ["routing", "dynamic_bidding", "cooldown_management"],
    cannot: ["strategy_generation", "response_generation", "content_filtering"],
    prefers: ["routing"],
    blacklist: [],
    typical_latency_ms: 1,
    max_latency_ms: 100,
    requires_llm: false,
    concurrent_capable: false,
    must_wait_for: ["amygdala"],
    optional_input_from: [],
    health: defaultHealth(),
  },

  salience: {
    region: "salience",
    can: ["attention_allocation"],
    cannot: ["strategy_generation", "response_generation", "content_filtering"],
    prefers: ["attention_allocation"],
    blacklist: [],
    typical_latency_ms: 1,
    max_latency_ms: 100,
    requires_llm: false,
    concurrent_capable: false,
    must_wait_for: [],
    optional_input_from: [],
    health: defaultHealth(),
  },
};
